export const aboutIntro = [
  "En el corazón de nuestra comunidad se encuentra el Ministerio Internacional Libertad en Cristo Jesús, un lugar donde la fe se entrelaza con la vida diaria, donde la esperanza se convierte en acción y donde las personas de todos los ámbitos de la vida se reúnen como una familia en Cristo. Desde el momento en que cruzas nuestras puertas, te recibimos con los brazos abiertos y el deseo sincero de ser un refugio espiritual en un mundo lleno de desafíos.",
  "Somos una iglesia comprometida con la autenticidad y la conexión genuina. Aquí, encontrarás una comunidad diversa de individuos unidos por una fe común en Jesucristo. Nuestro enfoque no se limita a los muros de nuestro edificio; nos esforzamos por ser una luz en nuestra comunidad y más allá, extendiendo la gracia y el amor de Cristo a través de acciones tangibles y palabras de aliento.",
  "En el Ministerio Internacional Libertad en Cristo Jesús, valoramos la adoración vibrante y la enseñanza bíblica sólida. Creemos en el poder de la oración y en la importancia de cultivar relaciones significativas dentro de nuestra comunidad. Aquí, encontrarás un lugar para crecer espiritualmente, un espacio para hacer preguntas, buscar respuestas y experimentar el amor transformador de Dios.",
  "Nuestro compromiso va más allá de los servicios de los domingos; buscamos marcar una diferencia en la vida de las personas, sirviendo a los necesitados, defendiendo la justicia y siendo un faro de esperanza para aquellos que atraviesan tiempos difíciles. En cada paso que damos como iglesia, nos esforzamos por reflejar el amor de Jesús y ser una influencia positiva en nuestro entorno.",
  "Te invitamos a formar parte de esta hermosa historia de fe, esperanza y comunidad. Ven tal como eres y únete a nosotros en esta emocionante jornada espiritual. En el Ministerio Internacional Libertad en Cristo Jesús, hay un lugar para ti."
]

export const aboutVision = [
  "En el Ministerio Internacional Libertad en Cristo Jesús, aspiramos a ser una comunidad donde la luz del amor de Dios brille intensamente, transformando vidas y permeando nuestra sociedad con esperanza y gracia. Visualizamos una iglesia donde cada individuo, sin importar su historia o circunstancias, encuentre un hogar espiritual; un lugar donde puedan cultivar una relación significativa con Dios y crecer en su fe de una manera auténtica y profunda.",
  "Buscamos ser más que un lugar de encuentro; anhelamos ser un faro de esperanza en nuestra comunidad y más allá. Visualizamos una congregación diversa unida por un propósito común: amar a Dios, amar a los demás y ser instrumentos de cambio positivo en el mundo que nos rodea.",
  "Nos esforzamos por ser una iglesia inclusiva, donde se celebre la diversidad y se fomente la unidad en Cristo. Visualizamos una comunidad donde cada persona se sienta valorada, aceptada y equipada para descubrir y cumplir el propósito que Dios tiene para sus vidas.",
  "Imaginamos un Ministerio Internacional Libertad en Cristo Jesús que trascienda las paredes de nuestro edificio, siendo activos agentes de transformación en nuestra sociedad. Visualizamos una iglesia que no solo proclame el Evangelio con palabras, sino que lo viva a través de acciones concretas de amor, servicio y compasión, impactando vidas y restaurando esperanzas.",
  "En resumen, nuestra visión es ser una iglesia que refleje el amor de Cristo en todo lo que hacemos, siendo una fuente de inspiración y un refugio espiritual para todos aquellos que buscan un camino de fe significativo y auténtico."
]

export const aboutMision = [
  "En el Ministerio Internacional Libertad en Cristo Jesús, nuestra misión es ser un testimonio vivo del amor redentor de Dios, impactando vidas a través de la enseñanza, el servicio y el ejemplo de Cristo. Nos comprometemos a ser una comunidad activa y comprometida, llevando el mensaje transformador del Evangelio a todos los rincones de nuestra sociedad.",
  "Buscamos compartir el mensaje de esperanza y salvación, no solo a través de nuestras palabras, sino también a través de nuestras acciones. Nuestra misión es ser una iglesia que no se conforma con quedarse dentro de sus paredes, sino que sale al mundo para marcar una diferencia tangible en la vida de las personas.",
  "Nos esforzamos por ser una iglesia inclusiva y acogedora, donde cada individuo se sienta amado, aceptado y capacitado para crecer espiritualmente. Nuestra misión es proporcionar un ambiente de crecimiento donde las personas puedan profundizar su relación con Dios, descubrir su propósito y potencial en Cristo, y encontrar un sentido de pertenencia y comunidad.",
  "Buscamos ser un faro de esperanza en medio de la oscuridad, sirviendo a los necesitados, defendiendo la justicia y elevando a los desanimados. Nuestra misión es ser manos y pies de Cristo en este mundo, llevando consuelo a los afligidos y proclamando la libertad que se encuentra en Jesús.",
  "En resumen, nuestra misión es vivir el Evangelio en todo momento, siendo luz en las tinieblas, extendiendo amor y esperanza a todos los que encuentren nuestro camino y mostrando el camino hacia la libertad y la plenitud que se encuentran en Cristo Jesús."
]
